# Generated by Django 2.1.3 on 2021-07-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_and_brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='type_model',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
