# Generated by Django 2.1.3 on 2021-07-14 03:11

import cars_and_brands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_and_brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, validators=[cars_and_brands.models.validate_brand_name_presence]),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=200, validators=[cars_and_brands.models.validate_car_name_presence]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=200, validators=[cars_and_brands.models.validate_car_year_presence]),
        ),
    ]
